### PR TITLE
Very important change to page title on index.html

### PR DESCRIPTION
**Pull request by scperkins**

### CODE REVIEW

**Comment by scperkins** [comment]
image

**Comment by scperkins** [comment]
image

**Comment by scperkins** [comment]
Better...
image

**Comment by EdgeCaseBerg** [comment]
:laughing: 
:shipit:

**Comment by EdgeCaseBerg** [comment]
For some reason the pizza rolls around the edges remind's me of hell.

**Comment by scperkins** [comment]
It's because pizza rolls give you diarrhea from hell?

**Comment by EdgeCaseBerg** [comment]
I have never had pizza rolls repeat on me or provide explosions of the underpants. You sir, are out of line! Insulting the glory of the rolls!

**Pull request closed without merging**
